name: run Next_Matches.py

on: 
  workflow_dispatch:
  schedule: 
    - cron: '*/5 * * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v2

      - name: instalar python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: instalar os pacotes do requirements.txt
        run: python -m pip install pip install -r requirements.txt

      - name: executar arquivo de scrapping
        run: python Next_Matches.py

      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push