name: run Next_Matches.py

on: 
  workflow_dispatch:
  

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v2

      - name: instalar python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Tentativa Chrome do site github setup-chromedriver
        uses: nanasess/setup-chromedriver@v1
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'

      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: instalar os pacotes do requirements.txt
        run: python -m pip install pip install -r requirements.txt

      - name: executar arquivo de scrapping
        run: python Next_Matches.py

      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push