name: Run Results Webscrapping on schedule

on:
  schedule: 
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: JeremiasDief/private-arquivos
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: private-arquivos

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller

    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
    - name: Install a new Chromium
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install ChromeDriver
      run: |
        python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"

    - name: Run the webscraping script
      env:
        BETEXPLORER_LOGIN: ${{ secrets.BETEXPLORER_LOGIN }}
        BETEXPLORER_PASSWORD: ${{ secrets.BETEXPLORER_PASSWORD }}
      run: |
        python Results.py

    - name: Commit and push to private repo
      run: |-
        cd private-arquivos
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date)
        git commit -m "Update with latest data: ${timestamp}" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}