name: Run Results Webscrapping on dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: JeremiasDief/private-arquivos
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: private-arquivos

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller

    - name: Install Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+')
        wget https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

    - name: Run the webscraping script
      env:
        BETEXPLORER_LOGIN: ${{ secrets.BETEXPLORER_LOGIN }}
        BETEXPLORER_PASSWORD: ${{ secrets.BETEXPLORER_PASSWORD }}
      run: |
        python Results.py

    - name: Commit and push to private repo
      run: |-
        cd private-arquivos
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date)
        git commit -m "Update with latest data: ${timestamp}" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
